{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b4ef844-8b2d-4ea6-aa21-88fdde4c1e2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "q1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dadfe36f-847e-4dd3-8a49-76101b599743",
   "metadata": {},
   "outputs": [],
   "source": [
    "exception are raised when programme is syntaticaly is corret but \n",
    "code resulted in an error.this error does not stop the excecutation of programme but it change the flow of code.\n",
    "syntax error:- a syntax error is an error which name suugest this type of error occur when we run a programme.when we wrongly write a code so we got an syntax error.\n",
    "exception error:- exception error also occur in run time.this error generated by executation time here code has no error it given by interpreter.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "815b2b15-e76b-413e-a581-b877c136d254",
   "metadata": {},
   "outputs": [],
   "source": [
    "q2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ffdeb0cf-0cc6-4c26-b144-36f9e64b740c",
   "metadata": {},
   "outputs": [],
   "source": [
    "when the exception is not handled it will cause the programme to terminate with an error message. Error include the information about which  type of exception is occured and location of programm where the exception is occured.\n",
    "\n",
    "try:\n",
    "\n",
    "    a=5\n",
    "    a/0\n",
    "except FileNotFoundError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4f8c809-7303-4743-b2a9-a7ebd946d9c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "q3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "861f4424-3c44-47a2-b05b-32db4dc76931",
   "metadata": {},
   "outputs": [],
   "source": [
    "in Python, you can catch and handle exceptions using the try...except statement. The basic syntax for this statement is:\n",
    "\n",
    "python\n",
    "Copy code\n",
    "try:\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "\n",
    "def divide(x, y):\n",
    "    try:\n",
    "        result = x / y\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: division by zero\")\n",
    "    except ValueError:\n",
    "        print(\"Error: invalid input\")\n",
    "    else:\n",
    "        print(\"Result:\", result)\n",
    "\n",
    "divide(10, 2)  \n",
    "divide(10, 0)  \n",
    "divide(\"10\", \"2\") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0eedb796-bf48-4d52-b5b0-a13d9a929583",
   "metadata": {},
   "outputs": [],
   "source": [
    "q4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7aa8b6f-4ae0-4bde-97d7-058a0cce5434",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:-try is used to handle the exception.satement which raised the exception are kept inside the try clause and  wrriten inside the try block. and except block catch the exception and handle exception.\n",
    "else:-else clause is present after all except clause and it will excecuted only once when try block not raised any exception .\n",
    "finally:-finally always exceuted after try except block . the final block always execute the normal termination of try block or try block terrminate due to exception.\n",
    "raise:- raise satatement force to programmer to raised a specific type of exception.the sole argument in raise indicate the exception to be raised.\n",
    "example\n",
    "class negative_age(Exception):\n",
    "    def __init__(self,message):\n",
    "        self.message=message\n",
    "def negativeage(age):\n",
    "    if age<0:\n",
    "        raise negative_age(\"age cannot be negative\")\n",
    "    else:\n",
    "        print(\"age is valid\")\n",
    "\n",
    "try:\n",
    "    age=int(input(\"enter thr age\"))\n",
    "    negative_age(age)\n",
    "\n",
    "except negative_age as e:\n",
    "    print(\"file is not found \",e)\n",
    "else:\n",
    "    print(\"try block executed suucessfully without any exception \")\n",
    "finally:\n",
    "    print(\"program is going to terminated\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c212dfe-5a2c-4ad4-b687-a9171142122b",
   "metadata": {},
   "outputs": [],
   "source": [
    "q5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ec3f2e0-c16c-493f-920a-f0bbd1e09fa2",
   "metadata": {},
   "outputs": [],
   "source": [
    "custom exception class is usser defined class which is created by developer for handling a specific error or handle a specific exception case.\n",
    "why we need custom exception class..\n",
    "when programme is not generate any type of error but at developer side it gave an error so we generate a cosutom class for handle specific error or exception case. \n",
    "# \"example:\"\n",
    "def negativeage(age):\n",
    "    if age<0:\n",
    "        raise negative_age(\"age cannot be negative\")\n",
    "    else:\n",
    "        print(\"age is valid\")\n",
    "\n",
    "try:\n",
    "    age=int(input(\"enter thr age\"))\n",
    "    negative_age(age)\n",
    "\n",
    "except negative_age as e:\n",
    "    print(\"file is not found \",e)\n",
    "else:\n",
    "    print(\"try block executed suucessfully without any exception \")\n",
    "finally:\n",
    "    print(\"program is going to terminated\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "227ae4ef-8152-4e8a-b8ee-ad77874c6a6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "q6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "46baeda9-7c35-4702-95b7-331d3881711b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
